feat: add file overwrite feature
mathisve/gdrive-upload-action pull request #9
Opened 2021-08-24 20:48 UTC by adityak74

This adds support to overwrite the file if required. overwrite: true can be passed in to specify that the file with the same needs to be updated/overwritten. Google Drive will manage the versioning of the file being updated/uploaded.

2021-08-24 20:51 UTC, adityak74 commented
@mathisve - This PR should be good for a review!

2021-09-18 20:12 UTC, Crejaud requested changes
Thanks for working on this. I have a use-case for an overwrite parameter as well here

2021-09-18 20:12 UTC, crejaud commented on LICENSE.md
> +THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMEN
Your IDE is probably adding extra characters at the end of each file. You'd probably want to revert this change

2021-09-18 20:12 UTC, Crejaud commented on main.go
> +		r, err := svc.Files.List().Do()
This is querying every single file in the directory, hence there is a bug in this diff. If there are files, but none of them match the `filename`, then nothing is uploaded to google drive. The expected behaviour would be to upload a new file.

Let's try querying the files by name instead using Q(). See https://pkg.go.dev/google.golang.org/api/drive/v3#FilesListCall.Q

Here is an explanation of the query syntax:
https://developers.google.com/drive/api/v3/search-files#query_string_examples

```
// Query for all files in google drive directory with name = <filename>
filenameQuery = fmt.Sprintf("name = '%s'", filename)
filesQueryCallResult, err := svc.Files.List().Q(filenameQuery).Do()

if len(filesQueryCallResult.Files == 0) {
  // upload file to drive
} else {
  // overwrite each file
}
```

2021-09-18 20:12 UTC, Crejaud commented on README.md
> +If you want to overwrite the filename with existing file, it will use the `filename`.
Given that `filename` is the file that is stored locally, and `name` is the preferred name to be displayed on google drive, shouldn't this support overwriting based on `name`? And if `name` is not provided, then use `filename`.

Using the `overwrite` parameter now rends `name` useless. This doesn't seem to be the preferred behaviour.

2021-09-18 20:12 UTC, Crejaud commented on main.go
> +	overwrite        = "false"
These style changes seem out of scope for this diff

2021-09-18 20:12 UTC, Crejaud commented on README.md
> +          name: "documentation.zip" # optional string
why the re-ordering?

2023-05-23 20:01 UTC, mathisve commented
Closed due to #20.

Still want to thank you @adityak74, @Crejaud and @asfaltboy for contributing!

2023-05-23 20:01 UTC, closed without merging